from __future__ import annotations

import logging
from typing import Optional

import numpy as np

logger = logging.getLogger(__name__)


def generate_tearsheet(
    equity_curve: list[float],
    returns: Optional[list[float]] = None,
    benchmark_returns: Optional[list[float]] = None,
    title: str = "Backtest Tearsheet",
    output_path: Optional[str] = None,
) -> str:
    try:
        import quantstats as qs
    except ImportError:
        logger.warning("quantstats not installed. Install with: pip install quantstats")
        html = _basic_html_tearsheet(equity_curve, returns, title)
        if output_path:
            with open(output_path, "w") as f:
                f.write(html)
        return html

    eq = np.array(equity_curve, dtype=float)
    if returns is None:
        rets = np.diff(eq) / np.maximum(eq[:-1], 1e-10)
    else:
        rets = np.array(returns, dtype=float)
    rets = np.nan_to_num(rets, nan=0.0)

    import pandas as pd
    ret_series = pd.Series(rets, name="Strategy")

    bench = None
    if benchmark_returns is not None:
        bench = pd.Series(np.array(benchmark_returns, dtype=float), name="Benchmark")

    try:
        if output_path:
            qs.reports.html(ret_series, benchmark=bench, title=title, output=output_path, download_filename=output_path)
            html = open(output_path).read()
        else:
            html = qs.reports.html(ret_series, benchmark=bench, title=title)
        return html
    except Exception as e:
        logger.warning("quantstats tearsheet failed: %s", e)
        return _basic_html_tearsheet(equity_curve, returns, title)


def _basic_html_tearsheet(
    equity_curve: list[float],
    returns: Optional[list[float]] = None,
    title: str = "Backtest Tearsheet",
) -> str:
    eq = np.array(equity_curve, dtype=float)
    if returns is None:
        rets = np.diff(eq) / np.maximum(eq[:-1], 1e-10)
    else:
        rets = np.array(returns, dtype=float)
    rets = np.nan_to_num(rets, nan=0.0)

    total_return = (eq[-1] / eq[0]) - 1 if eq[0] > 0 else 0.0
    n_years = len(rets) / 252
    ann_return = (1 + total_return) ** (1 / max(n_years, 0.01)) - 1
    ann_vol = float(np.std(rets) * np.sqrt(252))
    sharpe = ann_return / max(ann_vol, 1e-10)
    peak = np.maximum.accumulate(eq)
    drawdowns = (eq - peak) / peak
    max_dd = float(np.min(drawdowns))
    win_rate = float(np.sum(rets > 0) / max(len(rets), 1))

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{title}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, sans-serif; margin: 40px; }}
h1 {{ color: #1a1a2e; }}
.metrics {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin: 24px 0; }}
.card {{ background: #f8f9fa; border-radius: 8px; padding: 16px; }}
.card .value {{ font-size: 24px; font-weight: 700; color: #1a1a2e; }}
.card .label {{ font-size: 12px; color: #6c757d; text-transform: uppercase; }}
.positive {{ color: #28a745 !important; }}
.negative {{ color: #dc3545 !important; }}
</style></head><body>
<h1>{title}</h1>
<div class="metrics">
<div class="card"><div class="value {'positive' if total_return > 0 else 'negative'}">{total_return:.2%}</div><div class="label">Total Return</div></div>
<div class="card"><div class="value {'positive' if ann_return > 0 else 'negative'}">{ann_return:.2%}</div><div class="label">Annualized Return</div></div>
<div class="card"><div class="value {'positive' if sharpe > 1 else 'negative'}">{sharpe:.2f}</div><div class="label">Sharpe Ratio</div></div>
<div class="card"><div class="value negative">{max_dd:.2%}</div><div class="label">Max Drawdown</div></div>
<div class="card"><div class="value">{win_rate:.1%}</div><div class="label">Win Rate</div></div>
<div class="card"><div class="value">{ann_vol:.2%}</div><div class="label">Annualized Volatility</div></div>
<div class="card"><div class="value">{len(rets)}</div><div class="label">Total Trading Days</div></div>
<div class="card"><div class="value">{n_years:.1f}</div><div class="label">Years</div></div>
</div>
<p><em>Generated by Trading-Engine Tearsheet</em></p>
</body></html>"""
    return html
