from __future__ import annotations

from typing import Any


class PineScriptExporter:
    def __init__(self, version: str = "6"):
        self.version = version

    def export(self, strategy_name: str, indicators: list[dict], entry_conditions: list[str], exit_conditions: list[str], ticker: str = "AAPL") -> str:
        lines = [f"//@version={self.version}", f"strategy(\"{strategy_name}\", overlay=true, initial_capital=100000)"]
        for ind in indicators:
            name = ind.get("name", "")
            params = ind.get("params", {})
            if name == "sma":
                src = params.get("source", "close")
                period = params.get("period", 20)
                lines.append(f"sma_{period} = ta.sma({src}, {period})")
                lines.append(f"plot(sma_{period}, \"SMA {period}\", color=color.blue)")
            elif name == "ema":
                src = params.get("source", "close")
                period = params.get("period", 20)
                lines.append(f"ema_{period} = ta.ema({src}, {period})")
                lines.append(f"plot(ema_{period}, \"EMA {period}\", color=color.red)")
            elif name == "rsi":
                period = params.get("period", 14)
                lines.append(f"rsi = ta.rsi(close, {period})")
                lines.append(f"hline(30, \"Oversold\", color=color.green)")
                lines.append(f"hline(70, \"Overbought\", color=color.red)")
            elif name == "macd":
                fast = params.get("fast", 12)
                slow = params.get("slow", 26)
                signal = params.get("signal", 9)
                lines.append(f"[macd_line, signal_line, hist] = ta.macd(close, {fast}, {slow}, {signal})")
                lines.append("plot(macd_line, \"MACD\", color=color.blue)")
                lines.append("plot(signal_line, \"Signal\", color=color.orange)")
                lines.append("hline(0, \"Zero\", color=color.gray)")

        for cond in entry_conditions:
            lines.append(f"if ({cond})")
            lines.append("    strategy.entry(\"Long\", strategy.long)")
        for cond in exit_conditions:
            lines.append(f"if ({cond})")
            lines.append("    strategy.close(\"Long\")")

        lines.append(f"// Generated by Trading-Engine for {ticker}")
        return "\n".join(lines)
