from .bars_routes import router as bars_router
from .chart_routes import router as chart_router
from .ta_routes import router as ta_router
from .flows import router as flows_router
from .hedge_fund import router as hedge_fund_router
from .mmc import router as mmc_router
from .alpha_zoo_routes import router as alpha_zoo_router
from .geo_analysis_routes import router as geo_analysis_router
from .experiment_routes import router as experiment_router
from .swarm_routes import router as swarm_router
from .hypothesis_routes import router as hypothesis_router
from .china_markets_routes import router as china_markets_router
from .backtest_cache_routes import router as backtest_cache_router
from .protections_routes import router as protections_router
from .pairlists_routes import router as pairlists_router
from .debate_routes import router as debate_router
from .providers_routes import router as providers_router
from .mcp_routes import router as mcp_router
from .workflow_routes import router as workflow_router
from .hyperopt_routes import router as hyperopt_router
