POPULAR_SYMBOLS = [
    {"symbol": "AAPL", "description": "Apple Inc.", "type": "Common Stock"},
    {"symbol": "MSFT", "description": "Microsoft Corporation", "type": "Common Stock"},
    {"symbol": "GOOGL", "description": "Alphabet Inc.", "type": "Common Stock"},
    {"symbol": "AMZN", "description": "Amazon.com Inc.", "type": "Common Stock"},
    {"symbol": "TSLA", "description": "Tesla Inc.", "type": "Common Stock"},
    {"symbol": "META", "description": "Meta Platforms Inc.", "type": "Common Stock"},
    {"symbol": "NVDA", "description": "NVIDIA Corporation", "type": "Common Stock"},
    {"symbol": "NFLX", "description": "Netflix Inc.", "type": "Common Stock"},
    {"symbol": "ORCL", "description": "Oracle Corporation", "type": "Common Stock"},
    {"symbol": "CRM", "description": "Salesforce Inc.", "type": "Common Stock"},
    {"symbol": "JPM", "description": "JPMorgan Chase & Co.", "type": "Common Stock"},
    {"symbol": "V", "description": "Visa Inc.", "type": "Common Stock"},
    {"symbol": "WMT", "description": "Walmart Inc.", "type": "Common Stock"},
    {"symbol": "JNJ", "description": "Johnson & Johnson", "type": "Common Stock"},
    {"symbol": "PG", "description": "Procter & Gamble Co.", "type": "Common Stock"},
    {"symbol": "MA", "description": "Mastercard Inc.", "type": "Common Stock"},
    {"symbol": "UNH", "description": "UnitedHealth Group Inc.", "type": "Common Stock"},
    {"symbol": "HD", "description": "Home Depot Inc.", "type": "Common Stock"},
    {"symbol": "BAC", "description": "Bank of America Corp.", "type": "Common Stock"},
    {"symbol": "DIS", "description": "Walt Disney Co.", "type": "Common Stock"},
]

TRADINGVIEW_WIDGET_CONFIGS = {
    "symbol_info": lambda s: {
        "symbol": s.upper(),
        "colorTheme": "dark",
        "isTransparent": True,
        "locale": "en",
        "width": "100%",
        "height": 170,
    },
    "candle_chart": lambda s: {
        "symbol": s.upper(),
        "interval": "D",
        "theme": "dark",
        "style": "1",
        "locale": "en",
        "toolbar_bg": "#141414",
        "enable_publishing": False,
        "allow_symbol_change": False,
        "hide_side_toolbar": True,
        "width": "100%",
        "height": 600,
    },
    "technical_analysis": lambda s: {
        "symbol": s.upper(),
        "colorTheme": "dark",
        "isTransparent": True,
        "locale": "en",
        "width": "100%",
        "height": 400,
        "interval": "1h",
    },
    "company_profile": lambda s: {
        "symbol": s.upper(),
        "colorTheme": "dark",
        "isTransparent": True,
        "locale": "en",
        "width": "100%",
        "height": 440,
    },
}
